services:
  - type: web
    name: comparativo-politica-ipajm
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    healthCheckPath: /_stcore/health
